# -*- coding: utf-8 -*-
"""Files as embeddings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ttmd1COVSjipZUx8oHFL1y-l2X16zaG
"""

!pip install chromadb

!pip install sentence_transformers

import chromadb
import csv

import chromadb
import csv

def store_Function():
    """
    This function demonstrates how to interact with ChromaDB by creating a collection,
    uploading text and CSV files as embeddings, and querying the collection.
    """
    # Step 1: Get the Chroma Client
    chroma_client = chromadb.Client()

    # Step 2: Create a collection
    collection = chroma_client.create_collection(name="my_collections")

    # Step 3: Upload text files as embeddings
    text_files = ["file1.txt", "file2.txt"]  # List of text file paths

    for file_path in text_files:
        with open(file_path, 'r') as file:
            text_content = file.read()

        # Upload text content as embedding
        collection.add(
            documents=[text_content],  # Provide text content of the document
            metadatas=[{"source": "local_file"}],  # Add metadata for the document
            ids=[file_path]  # Provide the file path as the ID for the document
        )

    # Step 4: Upload CSV files as embeddings
    csv_files = ["data1.csv", "data2.csv"]  # List of CSV file paths

    for file_path in csv_files:
        with open(file_path, 'r') as file:
            csv_reader = csv.reader(file)
            csv_data = list(csv_reader)

        # Convert CSV data to text content
        text_content = '\n'.join(','.join(row) for row in csv_data)

        # Upload text content as embedding
        collection.add(
            documents=[text_content],  # Provide text content of the document
            metadatas=[{"source": "local_file"}],  # Add metadata for the document
            ids=[file_path]  # Provide the file path as the ID for the document
        )

    # Step 5: Query the collection (optional)
    results = collection.query(
        query_texts=["This is a query document"],
        n_results=2
    )

    # Note: Replace 'file1.txt', 'file2.txt', 'data1.csv', and 'data2.csv' with the actual paths to your text and CSV files.
    for result in results:
        print("Document:", result)
    print(results)

    for result in results:
        print("Document:", result)
    print(results)


    results = collection.query(
    query_texts=["This is a query document"],
    n_results=2
)

if __name__ == "__main__":
    store_Function()